# Generated by Django 5.2.7 on 2025-10-30 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título de la conversación generado automáticamente', max_length=200)),
                ('mode', models.CharField(choices=[('practice', 'Práctica con preguntas'), ('tutor', 'Tutoría con IA'), ('mixed', 'Modo mixto')], default='mixed', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la conversación')),
                ('is_active', models.BooleanField(default=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ejercicios.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('bot', 'Bot'), ('user', 'Usuario'), ('system', 'Sistema')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos: question_id, source, tokens_used, etc.', null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Tiempo de respuesta en milisegundos')),
                ('rating', models.IntegerField(blank=True, help_text='Calificación del usuario (1-5 estrellas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Feedback de Conversación',
                'verbose_name_plural': 'Feedbacks de Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_answer', models.CharField(max_length=10)),
                ('correct', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Tiempo que tardó en responder')),
                ('attempts', models.PositiveIntegerField(default=1, help_text='Número de intentos para esta pregunta')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='chatbot.conversation')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejercicios.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['student', '-last_activity'], name='chatbot_con_student_e871f9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['lesson'], name='chatbot_con_lesson__de0a43_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_cha_convers_f8ca66_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', '-date'], name='chatbot_res_student_f76130_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['question'], name='chatbot_res_questio_fb185c_idx'),
        ),
    ]
