# Generated by Django 5.2.7 on 2025-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AddField(
            model_name='user',
            name='telefono1',
            field=models.CharField(blank=True, help_text='Formato: 3001234567 o +573001234567', max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
